version: '3'
services:
  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    environment:
      PMA_HOST: 192.168.31.73
      PMA_PORT: 3306
    ports:
      - 8080:80

  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: allen
      # MONGO_INITDB_ROOT_PASSWORD: password
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # MONGO_INITDB_DATABASE: kaiji
    ports:
      - 27017:27017
    volumes:
      - '/home/allen/.mount/mongodb:/data/db'


