apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    run: crawler
  name: crawler

spec:
  schedule: "{{ .Values.cronjob }}"
  jobTemplate:
    spec:
      template:
        metadata:
            labels:
              run: crawler
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: Always
              volumeMounts:
                - name: config-volume
                  mountPath: /app/configs
              # command: ['sleep', 'infinity']
          volumes:
            - name: config-volume
              configMap:
                name: crawler-conf
          restartPolicy: Never
