cronjob: "3 23 * * *"

image:
  repository: allensyk/kaiji-crawler
  tag: latest

config:
  log:
    level: DEBUG

  timezone: Asia/Taipei

  commander:
    queryPeriod: 5 # second

  mongo:
    db: kaiji
    host: 10.0.0.68
    port: 27017
    username: 
    password: 